### ISSUE TITLE
How to work in  portrait mode

### ISSUE THREAD

**Issue by HelenXR** [OSVR/distortionizer#20]
This Application work fine in my monitor(1366x768) which is in landscape mode.
But My HMD devices is 1440x2560 which is in portrait mode, I need to rotate the View .
I want to find some api to do this  under Class QMainWindow & QWidget ,But I don't find ,give me a hand,thanks.

**Comment by russell-taylor** [comment]
The application does not have a portrait mode.  However, in Windows you can rotate the display within the OS so that it shows in landscape mode and run the program in that configuration.  The resulting parameters will work for a RenderManager context that is in portrait mode, it is only the distortionizer than should need to be run in landscape.
