### ISSUE TITLE
How to determine the best distortion effect

### ISSUE THREAD

**Issue by HelenXR** [OSVR/distortionizer#23]
Compile the project, generate the application "distortionizer-calibration.exe".
using Keyboard controls to adjust the screen display,But how to judge the best results?

**Comment by russell-taylor** [comment]
Commit 36129efddcb9d4f7278d8841311260e91ec4f1a8 added a description of how to do this to the README: To judge the results, pull the HMD out of DirectMode so that it shows up as a second display. Put it into Landscape mode. Move the distortion window onto the HMD's display and then use F to toggle fullscreen on. Look through the HMD and adjust the values to make red, green and blue line up and to make all of the lines straight. This is an optimization in a high-dimensional space, so be prepared for some frustration.

**Comment by HelenXR** [comment]
Thank you for your newest commit !
